### ISSUE TITLE
First picture: Replace SOTUS

### ISSUE THREAD

**Issue by nosrednaharas** [naffis/presidential-libraries#3]
First picture: Replace SOTUS
The Big Three being photographed at the Tehran Conference, 11/29/43.
http://tmblr.co/ZI1-WxYE9JKG

**Comment by nosrednaharas** [comment]
Sets the tone. We’re taking well known pictures and giving you behind the scenes information.

**Comment by ThisIsJ** [comment]
I've shared this high res photo through Drive with you.

**Comment by naffis** [comment]
Please verify and close.
